Close generated tests tab, if all test were deleted
JetBrains-Research/TestSpark pull request #331
Opened 2024-08-30 15:45 UTC by arksap2002

# Description of changes made
If user will manually delete all tests, the tab have to be closed.

# Other notes
Closes #330 
- [x] I have checked that I am merging into correct branch

2024-09-17 14:14 UTC, pderakhshanfar approved these changes

2024-09-25 11:42 UTC, Vladislav0Art requested changes

2024-09-25 11:42 UTC, Vladislav0Art commented on src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt
> +        if (generatedTestsTabData.testCasePanelFactories.size == numberOfRemovedTests) {
The code will be easier to read if we use stream API here:
```kotlin
// ATTENTION: I did not test these expressions; only re-wrote the existing code
val passedTestsCount = generatedTestsTabData.testCasePanelFactories
            .filter { !it.isRemoved() }
            .count { it.getError()?.isEmpty() == true }
            
val removedTestsCount = generatedTestsTabData.testCasePanelFactories.count { it.isRemoved() }
``` 
Working with immutable variables makes coding reading easier here.

2024-09-30 16:34 UTC, Vladislav0Art approved these changes

2024-09-30 16:35 UTC, merged