Set fixed size of the requestComboBox
JetBrains-Research/TestSpark pull request #343
Opened 2024-09-02 15:52 UTC by arksap2002

# Description of changes made
When the prompt in the input field under "modify with LLM" gets length, it is impossible to send the request because the input field overflows over the send button.

# Why is merge request needed
*Please write why your merge request is needed*

# Other notes
Closes #313 

- [x] I have checked that I am merging into correct branch

2024-09-17 15:16 UTC, pderakhshanfar requested changes

2024-09-17 15:16 UTC, pderakhshanfar commented on src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
> +    private val removeButton = IconButtonCreator.getButton(TestSparkIcons.remove, PluginLabelsBundle.get("removeTip"))
Why did you change this line?

2024-09-17 15:16 UTC, pderakhshanfar commented on src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
> +            NotificationGroupManager.getInstance().getNotificationGroup("Test case copied").createNotification(
Same here

2024-09-17 15:16 UTC, pderakhshanfar commented on src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
> +        val newTestCase = TestProcessor(project).processNewTestCase(
And here

2024-09-17 15:16 UTC, pderakhshanfar commented on src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
> +        testCase.testName = TestAnalyzerFactory.create(language)
same comment

2024-09-17 15:16 UTC, pderakhshanfar commented on src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
> +        requestComboBox.preferredSize = Dimension(
Can you add comment about this change?

2024-09-30 16:27 UTC, Vladislav0Art requested changes

2024-10-01 18:15 UTC, Hello-zoka commented on src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
> +            languageTextField.preferredSize.height - requestJLabel.preferredSize.height - sendButton.preferredSize.height - 20,
I agree; such implementation looks a lot better. Nitpick: you can even write:
`requestComboBox.preferredSize = Dimension()`

2024-10-04 10:13 UTC, Vladislav0Art approved these changes

2024-10-04 10:17 UTC, Hello-zoka approved these changes

2024-10-04 10:37 UTC, Vladislav0Art commented on src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
> +        val newTestCase = TestProcessor(project).processNewTestCase(
Outdated. No change here.

2024-10-04 13:11 UTC, pderakhshanfar approved these changes

2024-10-04 13:48 UTC, merged