Locate `kotlinc` filepath via IntelliJ IDEA's bundled Kotlin plugin
JetBrains-Research/TestSpark pull request #376
Opened 2024-10-07 16:27 UTC by Vladislav0Art

# Description of changes made
Retrieves kotlin compiler (`kotlinc`) via `KotlinPluginLayout` component of `org.jetbrains.kotlin` bundled plugin.

# Why is merge request needed
Closes #311 

*Please write if you have anything to add*

# What is missing?
* [ ] Test the solution on Windows (test whether Windows has `kotlinc.exe` as a compiler).

- [x] I have checked that I am merging into correct branch

2024-10-08 16:04 UTC, pderakhshanfar requested changes
1. RuntimeExceptions in `KotlinTestCompiler`, `JavaTestCompiler`, and `TestCompilerFactory` shoudl be handled properly.
2. Since we are using path to `kotlinc`, the if condition for checking the error message [here](https://github.com/JetBrains-Research/TestSpark/blob/5975b97b5238ac2755c76d53405b09deef63371f/core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt#L67) might not work as expected.

2024-10-09 11:59 UTC, arksap2002 requested changes
Remaining message: https://github.com/JetBrains-Research/TestSpark/pull/376#issuecomment-2400093853

2024-10-09 21:09 UTC, Vladislav0Art commented on src/main/kotlin/org/jetbrains/research/testspark/tools/factories/TestCompilerFactory.kt
> +            throw RuntimeException("Java SDK not configured for the project.")
Now, throwing a custom exception that is handled in `Pipeline` and `Llm`.

2024-10-09 21:10 UTC, Vladislav0Art commented
> @Vladislav0Art where do you catch new `RuntimeException`?

[Solved](https://github.com/JetBrains-Research/TestSpark/pull/376#discussion_r1794233202).

2024-10-09 21:38 UTC, Vladislav0Art commented
> 2\. Since we are using path to `kotlinc`, the if condition for checking the error message [here](https://github.com/JetBrains-Research/TestSpark/blob/5975b97b5238ac2755c76d53405b09deef63371f/core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt#L67) might not work as expected

@pderakhshanfar 

This error message is outputted by a CLI, not kotlinc. I removed it because the custom exception thrown above in the init block does not allow `kotlinc` to be absent (because we literally search for an executable with this name; if it was not found in the init block, we'd throw an exception there).

2024-10-09 22:59 UTC, arksap2002 approved these changes

2024-10-10 09:52 UTC, pderakhshanfar approved these changes

2024-10-10 11:01 UTC, merged